name: brookz
favicon: null
layout_spectrum: 0.4577533390838653
typography_spectrum: 0.5303804464638233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.765923168277368
  lightness: 0.7111545440275222
  saturation: 0.07802823279052973
  rhythmicContrast: 0.8246535370126367
purpose: []
